### ISSUE TITLE
ACM repo initialization takes forever

### ISSUE THREAD

**Issue by laurentgrangeau** [GoogleCloudPlatform/federated-learning#335]
Here is the log:
╷
│ Error: local-exec provisioner error
│ 
│   with null_resource.init_acm_repository,
│   on tenant-configuration.tf line 30, in resource "null_resource" "init_acm_repository":
│   30:   provisioner "local-exec" {
│ 
│ Error running command
│ '"/home/lgrangeau/github.com/googlecloudplatform/federated-learning/terraform/scripts/init-acm-repository.sh" \
│   "./acm-repo-path" \
│   "https://source.developers.google.com/p/lgu-demos/r/fl-configsync" \
│   "main"
│ ': signal: interrupt. Output: Cloning into './acm-repo-path'...

I had to interrupt it because it has been running for like 15mn before interrupting

**Comment by laurentgrangeau** [comment]
Ok, it seems that it's related to some king of popup I have in VSCode asking for username and password I didn't see (or didn't show ?) the first time

**Comment by ferrarimarco** [comment]
/shrug

Please, reopen if it happens again.
