### ISSUE TITLE
"error: local-exec provisioner error" requires explicit gcloud authentication

### ISSUE THREAD

**Issue by eeaton** [GoogleCloudPlatform/federated-learning#412]
I encountered an edge case with Authentication when the code is running outside of Cloud Shell.

**Issue:**
It is required to set both Application Default Credentials (for Terraform) and gcloud credentials (for gcloud credentials in the scripts, such as the help function to get cluster credentials).
This is a bit non-intuitive, because normally when I deploy terraform assets I expect that only ADC is needed.  

However, when running on my local workstation, I set ADC only with `gcloud auth application-default login`, then run most of the `terraform apply` successfully, but it fails near the end due to missing gcloud credentials.  (error copied below).

```
Error: local-exec provisioner error
│ 
│   with module.kubectl_asm_wait_for_controlplanerevision_custom_resource_definition.module.gcloud_kubectl.null_resource.run_command[0],
│   on .terraform/modules/kubectl_asm_wait_for_controlplanerevision_custom_resource_definition/main.tf line 231, in resource "null_resource" "run_command":
│  231:   provisioner "local-exec" {
│ 
│ Error running command 'PATH=/google-cloud-sdk/bin:$PATH
│ .terraform/modules/kubectl_asm_wait_for_controlplanerevision_custom_resource_definition/modules/kubectl-wrapper/scripts/kubectl_wrapper.sh
│ tp-w europe-west1 myprojectid false false /bin/sh -c 'while ! kubectl wait
│ crd/controlplanerevisions.mesh.cloud.google.com --for condition=established --timeout=60m
│ --all-namespaces; do echo "crd/controlplanerevisions.mesh.cloud.google.com not yet available, waiting...";
│ sleep 5; done'
│ ': exit status 1. Output: + '[' 8 -lt 5 ']'
│ + CLUSTER_NAME=tp-w
│ + LOCATION=europe-west1
│ + PROJECT_ID=myprojectid
│ + INTERNAL=false
│ + USE_EXISTING_CONTEXT=false
│ + ENABLE_IMPERSONATE_SERVICE_ACCOUNT=/bin/sh
│ + IMPERSONATE_SERVICE_ACCOUNT=-c
│ + shift 5
│ + false
│ + RANDOM_ID=26965_30807
│ + export TMPDIR=/tmp/kubectl_wrapper_26965_30807
│ + TMPDIR=/tmp/kubectl_wrapper_26965_30807
│ + trap cleanup EXIT
│ + mkdir /tmp/kubectl_wrapper_26965_30807
│ + export KUBECONFIG=/tmp/kubectl_wrapper_26965_30807/config
│ + KUBECONFIG=/tmp/kubectl_wrapper_26965_30807/config
│ ++ grep -o -
│ ++ wc -l
│ + LOCATION_TYPE=1
│ + CMD='gcloud container clusters get-credentials tp-w --project myprojectid'
│ + [[ /bin/sh == true ]]
│ + [[ 1 -eq 2 ]]
│ + CMD+=' --region europe-west1'
│ + false
│ + gcloud container clusters get-credentials tp-w --project myprojectid --region europe-west1
│ Fetching cluster endpoint and auth data.
│ ERROR: (gcloud.container.clusters.get-credentials) ResponseError: code=401, message=Request had invalid
│ authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication
│ credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
│ + cleanup
│ + rm -rf /tmp/kubectl_wrapper_26965_30807
```

After I explicitly reauthenticate with `gcloud auth login`, then `terraform apply` can complete successfully.

It might be a common issue in customer environments if they follow security best practices to set a reauth policy for [Google Cloud Session length](https://support.google.com/a/answer/9368756?hl=en), and this is also enabled by default for new customer orgs since 2023.

**Suggested fix:** 
In the initial setup and troubleshooting directions, add a note that if you're running terraform in an environment other than CloudShell, you have to explicitly set both `gcloud auth login` && `gcloud auth application-default login` with the credentials of the principal deploying the resources.

When running in Cloud Shell, both of these are automatically set to your user identity without any deliberate configuration, so the directions as written can avoid this edge case. However, for those running outside of CloudShell, this could help reduce friction.

**Comment by ferrarimarco** [comment]
Hi @eeaton !

The module mentioned in the log is a wrapper around `gcloud`, so it's expected to use application default credentials if available.

What if you re-run `gcloud auth application-default login` instead of `gcloud auth login`?
